<tr>
    <td>COMISIONES DEVENGADAS POR OTORGAMIENTO DE GARANTIAS EN EL PERIODO</td>
    <td>COMISIONES DEVENGADAS POR GARANTÍAS OTORGADAS EN PERÍODO PREVIOS</td>
    <td>COMISIONES DEVENGADAS POR ADMINISTRACION DE FONDO DE RIESGO</td>
    <td>COMISIONES DEVENGADAS POR ASESORAMIENTO</td>
</tr>
<tr>
    <th>1</th>
    <th>2</th>
    <th>3</th>
    <th>4</th>
</tr>